### ISSUE TITLE
customized pods query and filtering

### ISSUE THREAD

**Issue by smatzis** [pods-framework/pods-beaver-builder-themer-add-on#50]
Hello and many thanks for this wonderful plugin!

Is there a way to exclude the rendering of the current post from the loop of a customized pods query (relation from current item) created with the posts module of beaver builder?

_(eg There are 2 pods: books and authors. There are also relationship fields for books->authors and authors->books written.
There is a singular theme layout for the template of the book and there is a need to have a row under the book image and info that shows other books by this author.
So BB Posts Module is used and customized pods query -> relation from current item is selected to show the books written by the author of the current book displaying.
The problem is that this method displays all the books written by the author and it does not exclude the current book displaying.)_

Another use of this kind of filtering is when someone wants to create a related posts query to use in a theme layout. This would be great too!

_(eg show all the custom posts that have at least one same custom taxonomy with the post currently displaying)_

Many thanks in advance!

**Comment by smatzis** [comment]
Hello Bernhard, how are you?
Is there any progress on this? Do you have something in mind?

Regards

**Comment by quasel** [comment]
i have an idea - but currently your best approach might be the use of a filter :/ thing is I'm not sure if this should be an option or excluded by default - like exclude the current item always as it makes rarely sense to display it? what's your take on that?

**Comment by smatzis** [comment]
Well, thanks for asking. Very kind! :) I think the best approach would be a checkbox to activate/deactivate the exclusion of displaying the current item. However i guess you are right that in most cases, users want current item excluded by default.
If you see it globally, i think the addition of logic actions (+,-,=,>,<, etc) would allow advanced queries.
Like show all posts that have same taxonomy as the current or don't show posts with creation date > the current. This would cover the previous example and further improve functionality!
Sorry if this is too hard or needs very much time. I only mean to make a proposion. I don't deeply understand how difficult it is to implement...

**Comment by sander-p** [comment]
Adding this enhancement would really help me as well. I think the current item should be excluded by default; I can't easily imagine a situation where including it would be useful. Maybe a separate option to include it is not even necessary.

Thanks for a great plugin!

**Comment by jimtrue** [comment]
Typically, shouldn't this be handled directly through the relationship field and not have to be a separate query? What are you putting into your 'customized query'?

**Comment by sander-p** [comment]
@jimtrue You're probably right.

As for the query: the beauty of the Beaver Builder Themer add on is of course that (as an end user) you don't need a custom query. You can simply choose "Relation from current item" for Pods Content Source. Or am I misunderstanding you?

**Comment by jimtrue** [comment]
@sander-p In your notes above, you say:

> Is there a way to exclude the rendering of the current post from the loop of a customized pods query (relation from current item) created with the posts module of beaver builder?

By default the relationship field field-connector should only be pulling items that are related to the current post through the relationship field in the current post, so there's no way they _could_ pull the current post, because the current post wouldn't be related to itself, unless I'm misunderstanding what you folks are requesting above.

**Comment by jimtrue** [comment]
@smatzis What are you using to specify other books by this author? Are you using a customized query? Because what you're asking for to be 'automatic' is to show all elements from the current author through it's relationship field. That's never going to exclude the book > author > books item because that would be a messy default. You'd have to use a customized query to specifically call from 'books' all books where author = current author for this book and NOT the current book.

That's not something we would 'enhance' in Beaver Themer add-on, that's something where you'd have to write a customized query for your special request, I believe, but I'll wait for @quasel 's feedback as well.

**Comment by jimtrue** [comment]
This comes more from putting two different post modules on the same page and expecting one to recognize automatically that it's supposed to exclude something just because it happens to be a books module on a singular book page. Yes, logically, you want it to exclude the current 'post', but you have to create that decision. It can't just be a checkbox because you're creating that connection through a traversal through two different relationship fields.

**Comment by sander-p** [comment]
I see what you mean – I think. But I also think this will be a very common use for the Beaver Themer add-on. Think of it as a related posts-like functionality.

If the add-on is not the right place for this, maybe it is something that could be implemented in Pods itself? Writing a customized query is probably beyond a lot of end users looking for this sort of functionality.

**Comment by jimtrue** [comment]
I'd unfortunately have to disagree, it's not a related posts kind of thing, "it's a related posts of a field in this related posts that pull a list of other related items but exclude one item based on other conditions". If the post in question had _seven_ relationships (not an unheard thing, believe me) there's not a way we could build a friendly interface for that. 

Sometimes, you just have to learn how to build WP Queries, which is what most of these are. We simplify them with our Pods where clauses and magic tags, but you still have to do the math (pull a set based on conditions that match, but exclude this set based on other conditions that match).

**Comment by jimtrue** [comment]
@sander-p Believe me, I feel your pain. I was frustrated by stuff like this when I first got started with Pods, too. Every challenge we face when building sites teaches us something new. We can't create things that build everything; we have to focus on the most common use cases and make it somewhat easy to add 'custom queries' that work with what Beaver Themer provides.

**Comment by smatzis** [comment]
Hello i hope i am not late! how are you guys? If this is difficult or time consuming or for whatever reason you don't think it's good to implement this feature it's ok in my point of view. We already thank you so much for your work! Below you can see how it looks like in the post module settings of our fellow elementor page builder. I think it will be very useful if there was a checkbox and would not have to write custom queries every time we needed the current post excluded.
![template-block](https://user-images.githubusercontent.com/6583607/33727167-f25a35b6-db7f-11e7-9363-f6d2dbf47e31.jpg)

**Comment by jimtrue** [comment]
@smatzis That's actually not the same, though I could see where you'd think it might be. 

What you're showing is a common query to pull all of the same post type and just exclude the current post. That's fairly easy.

You're asking the posts-module to build a set of posts that are actually based on one value from the current post (the author), pull a list of related post based on that value and _then_ exclude the current post. Not the same thing at all. Go look back at my discussion above about the possibility of 7 different related fields and you can see the type of predicament we'd run into.

**Comment by jimtrue** [comment]
when I have to pull a list of items like that in a query we're one:

select all 'books' where ( related author.ID = current post's author.ID )  AND (ID != current post ID)

My thought would be, if it's going to exclude the current post and that's the functionality that should be in _all post modules_, that functionality needs to be a setting in Beaver Builder. Our field connector would just build the primary query (related books) though you'd still need a custom query to build it off the current 'author' or authors of the current post/book since the relationship field is _again_ in this case pulling related authors, not related books of the related authors (you're in an inception traversal loop).

**Comment by jimtrue** [comment]
btw, a query like this:
select all 'books' where ( related author.ID = current post's author.ID ) AND (ID != current post ID)

Is fairly easy to 'write'; building a UI that actually accomplishes that? Not so easy at all, because we'd have to give you a drop-down for all the relationship fields, pick a field from those related records based on whichever relationship field you picked and then pick another relationship field that drives _this_ query and _then_ don't show the current post in whatever set you build. If you only have 1 relationship field, not so confusing. Something with more than 5 with interconnections between those relationships to other posts... yikes.

**Comment by smatzis** [comment]
I don't know if i am wrong but beaver builder's post module allows only one traversal by default like the query you wrote above. I mean i don't understand a case of more than 1 relationship that someone would need this functionality. Do you have an example in mind? I can only think of books written by authors...

**Comment by sander-p** [comment]
@jimtrue I can see the potential pitfalls. I understand that a customized query is the way to go.
My point is that the scenario @smatzis outlined in the original message seems to me a prime example of common use. You've been very patient explaining the difficulties (thanks!). I'm just worried that your patience will be severely tested by all the requests for exactly this option 😉

**Comment by jimtrue** [comment]
Related Properties in a specific Zip code for this Realtor
Related Students in a  Class by a Specific Teacher or Teachers that teach the Same Class

There are honestly Thousands of possibilities when you start connecting your Content together.

And when it comes down to it: the posts module should have the option to always Exclude the current post (that's what you're requesting).

The reason there's a custom query option is for cases like this. And it's not about us getting overwhelmed for requests for this, it's more about you as a Website Builder/Designer understanding how your Content connects together so it's pretty easy to say 'gimme all students from this class that this teacher teaches" or "all teachers that also teach this class at different schools". It's not about the commonality of the question, it's about understanding how to ask the right question/query to get what you're looking for. Pods already provides you a fairly simple way to build these kinds of queries, it just takes some thought and patience to understand how they connect and work out the math to build the set you're looking for. At least we're not making you write it in PHP ;)

**Comment by smatzis** [comment]
Ok Jim i believe you are right about this. I did not understand how complicated it could become. :)

**Comment by jimtrue** [comment]
@smatzis and @sander-p Thank you! 

Believe me, I feel your frustration. We are also happy to help you understand how to write these custom queries. It does require understanding your content, the fields that make it up and how they connect through the relationship fields, but it's all learnable ;) And it requires patience.

**Comment by smatzis** [comment]
Thank you! I 'll give it a try to learn how to make an advanced custom pods query for this through documentation again. The first time i spent a week reading and i didn't manage to achieve the result i needed with the books and authors... Do you have a proposition on what to read to accomplish this?

**Comment by jimtrue** [comment]
Our Find Documentation and Find PodsCast is actually the best place to get an overview of how our fields 'traverse' and how to word your queries.

https://pods.io/docs/code/pods/find/
https://pods.io/2015/02/28/podscast-001-finding-your-way-with-podsfind/

the 'where' clause it built around those kinds of things. You can also join our Slack Chat at https://pods.io/chat/ which is probably the fastest way to get help.

**Comment by smatzis** [comment]
Ok thank you Jim and sander-p and Bernhard!
