### ISSUE TITLE
Default image for image field connection does not work

### ISSUE THREAD

**Issue by codente** [pods-framework/pods-beaver-builder-themer-add-on#67]
## Issue Overview
If you connect a pods image field to a photo module, you can add a default image for when the field is empty but it does not show the default image.

## Expected Behavior
The default image shows when the field is empty

## Current Behavior
The default image is not shown.

## Steps to Reproduce (for bugs)

1. Add a pods image field to a CPT
2. Add a photo module to a singular layout, for example, and connect the pods image field to the Photo module image field
3. Add a default image when asked
4.  View a post that has that Pods image field blank and the default image is not shown
5.  If a post has an image in the image field, that image DOES get shown so that is not an issue.

**Comment by Masti81** [comment]
Just to say i am following this issue too, looking forward to any solution / fix for it.

**Comment by quasel** [comment]
Sorry that the fix took so long :( shame on me thought it would be more complicated! You can test using the current 1.x Branch - will add some more stuff

**Comment by Masti81** [comment]
Thanks for looking into it quasel. However, i am not sure what you mean by "test using the current 1.x Branch" ? 

I have the following installed on my site and both are saying they are the lateset availale versions: 
Pods - Custom Content Types and Fields Version 2.7.4 
Pods Beaver Themer Add-On  1.2.1 |

What do i need to do to get your new fix for the issue?
Many thanks

**Comment by codente** [comment]
@quasel looks good :)

**Comment by quasel** [comment]
Just pushed a 1.2.2 Maintenance Release to WP.org Repo can take a bit of time until their caching updates :D 

@Masti81 you can always download the files from the Github Repository the green Button in the top right (just take care of the right Branch - but be carefull ;) ) 

Or you can use e.g https://github.com/afragen/github-updater to fetch it from Your WordPress admin - just be carefull as sometimes the 1.x Branch can have Bugs ;)

**Comment by codente** [comment]
@quasel whoot for easy fixes, right?

**Comment by Masti81** [comment]
Fantastic, just managed to update it, all good now. Thank you very much!

**Comment by Masti81** [comment]
Hello, 

I think an issue related to this is occurring for me . Although instead of on a photo module it is a themer part row image.

- The rows image field is connecting to a PODS extended page field. If this field is left
null then a default fallback image is set to apply instead.  

 -The default image will display for pages, the problem we have is that for products and posts, if this field is null then it will just 
ignore the fallback image. 

POD: page(post type - extended) > Field: header_image

BB THEMER: http://shedcraft.ascet.co/fl-theme-layout/page-title-with-image-and-slogan/?fl_builder
a page:      http://shedcraft.ascet.co/online-shop/
a product:   http://shedcraft.ascet.co/product/jungle-fort-stained-ex-display/
a post:      http://shedcraft.ascet.co/things-to-consider-when-installing-a-garden-shed/

Beaver Builder Plugin (Pro Version) Version 2.2.2.6
Beaver Themer Version 1.2.3.4 
Pods - Custom Content Types and Fields Version 2.7.12 
Pods Beaver Themer Add-On Version 1.3.2 

Please can you assist with this again?
